version: '3.8'

services:

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    restart: always
    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "6543:5432"
    volumes:
      - stats-db-data:/var/lib/postgresql/data

  stats-server:
    build: ./ewm-stats-service/ewm-stats-server
    container_name: stats-server
    restart: always
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    restart: always
    environment:
      POSTGRES_DB: ewm
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "6544:5432"
    volumes:
      - ewm-db-data:/var/lib/postgresql/data

  ewm-service:
    build: ./ewm-main-service
    container_name: ewm-service
    restart: always
    depends_on:
      - ewm-db
      - stats-server
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ewm-db:5432/ewm
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

      STATS_SERVER_URL: http://stats-server:9090

volumes:
  stats-db-data:
  ewm-db-data:
